--- 
hosts_file: 
  - 
    domainname: domainname.tld
    hostname: gwy
    ip: "10.1.1.1"
  - 
    domainname: domainname.tld
    hostname: fileserver
    ip: "10.1.1.2"
  - 
    domainname: domainname.tld
    hostname: web
    ip: "10.1.1.3"
